#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Geekzone.Resource", IsApplication=true)]

namespace Geekzone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.components.stickylistheaders.Resource.String.ApplicationName = global::Geekzone.Resource.String.ApplicationName;
			global::com.refractored.components.stickylistheaders.Resource.String.Hello = global::Geekzone.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int countries = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int buttons = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int emailMeCheckBox = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int list = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int loginButton = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int passwordEditText = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int postReplyButton = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int replyEditText = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int text1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int threadWebView = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int usernameEditText = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int forumItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listViewSection = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int viewForum = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int viewThread = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int webViewForum = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
